export const genres = [
  "Pop Rock",
  "House",
  "Vocal",
  "Experimental",
  "Punk",
  "Synth-pop",
  "Alternative Rock",
  "Techno",
  "Indie Rock",
  "Soul",
  "Disco",
  "Ambient",
  "Hardcore",
  "Folk",
  "Country",
  "Ballad",
  "Hard Rock",
  "Electro",
  "Rock & Roll",
  "Chanson",
  "Trance",
  "Heavy Metal",
  "Psychedelic Rock",
  "Romantic",
  "Folk Rock",
  "Downtempo",
  "Soundtrack",
  "Noise",
  "Schlager",
  "Prog Rock",
  "Classic Rock",
  "Funk",
  "Easy Listening",
  "Black Metal",
  "Tech House",
  "Blues Rock",
  "New Wave",
  "Rhythm & Blues",
  "Deep House",
  "Industrial",
  "Classical",
  "Death Metal",
  "Drum n Bass",
  "Progressive House",
  "Euro House",
  "Soft Rock",
  "Garage Rock",
  "Abstract",
  "Minimal",
  "Europop",
  "Gospel",
  "Acoustic",
  "Thrash",
  "Baroque",
  "Swing",
  "Modern",
  "Big Band",
  "Dub",
  "Country Rock",
  "Contemporary Jazz",
  "Breakbeat",
  "Drone",
  "Indie Pop",
  "Progressive Trance",
  "Opera",
  "Holiday",
  "Dancehall",
  "IDM",
  "Contemporary",
  "RnB/Swing",
  "Breaks",
  "African",
  "Reggae",
  "Art Rock",
  "Dark Ambient",
  "Fusion",
  "Post-Punk",
  "Doom Metal",
  "Gangsta",
  "Avantgarde",
  "Religious",
  "Pop Rap",
  "Dance-pop",
  "Hard Trance",
  "Beat",
  "Rockabilly",
  "Electro House",
  "Acid",
  "Instrumental",
  "Jazz-Funk",
  "Roots Reggae",
  "Lo-Fi",
  "Comedy",
  "Score",
  "Contemporary R&B",
  "Theme",
  "Grindcore",
  "Leftfield",
  "Ska",
  "Post Rock",
  "Dubstep",
  "Soul-Jazz",
  "Spoken Word",
  "Power Pop",
  "Psy-Trance",
  "Glam",
  "Hip Hop",
  "Salsa",
  "New Age",
  "Modern Classical",
  "Bop",
  "Bolero",
  "Goth Rock",
  "Conscious",
  "Jazz-Rock",
  "Hard House",
  "Free Improvisation",
  "Trip Hop",
  "Cumbia",
  "Emo",
  "Musical",
  "Latin Jazz",
  "Italo-Disco",
  "Stoner Rock",
  "J-pop",
  "EBM",
  "Volksmusik",
  "MPB",
  "Surf",
  "Shoegaze",
  "Hard Bop",
  "Jungle",
  "Free Jazz",
  "Doo Wop",
  "Field Recording",
  "Garage House",
  "Story",
  "Oi",
  "Hardstyle",
  "Samba",
  "Pop Punk",
  "Tango",
  "Cool Jazz",
  "Synthwave",
  "Darkwave",
  "Celtic",
  "Radioplay",
  "Post Bop",
  "Happy Hardcore",
  "Bluegrass",
  "Laïkó",
  "Choral",
  "UK Garage",
  "Vaporwave",
  "Eurodance",
  "Tribal",
  "Novelty",
  "Smooth Jazz",
  "Polka",
  "Flamenco",
  "Metalcore",
  "Trap",
  "Grunge",
  "Italodance",
  "Hardcore Hip-Hop",
  "Dixieland",
  "Progressive Metal",
  "Arena Rock",
  "Southern Rock",
  "Symphonic Rock",
  "AOR",
  "Future Jazz",
  "Latin",
  "Hindustani",
  "Nu Metal",
  "Parody",
  "Rumba",
  "Glitch",
  "Harsh Noise Wall",
  "Cha-Cha",
  "Krautrock",
  "Space Rock",
  "Boom Bap",
  "Dub Techno",
  "Power Metal",
  "Gabber",
  "Merengue",
  "Audiobook",
  "Bossa Nova",
  "Hi NRG",
  "Speed Metal",
  "Thug Rap",
  "Kayōkyoku",
  "Breakcore",
  "Neo-Classical",
  "Bollywood",
  "Poetry",
  "Jazzy Hip-Hop",
  "Power Electronics",
  "Reggae-Pop",
  "Acid House",
  "Avant-garde Jazz",
  "Boogie",
  "Musique Concrète",
  "Ranchera",
  "Post-Hardcore",
  "Renaissance",
  "Electric Blues",
  "Marches",
  "Mod",
  "Dungeon Synth",
  "Mambo",
  "Sludge Metal",
  "Freestyle",
  "Acid Jazz",
  "Chiptune",
  "Country Blues",
  "Bossanova",
  "Minimal Techno",
  "Big Beat",
  "Interview",
  "Tribal House",
  "Bass Music",
  "Math Rock",
  "Calypso",
  "Modal",
  "Berlin-School",
  "Broken Beat",
  "Chicago Blues",
  "Nu-Disco",
  "Indian Classical",
  "Rocksteady",
  "Neofolk",
  "Ethereal",
  "Light Music",
  "Psychedelic",
  "Education",
  "Afrobeat",
  "Crust",
  "Neo Soul",
  "Britpop",
  "Afro-Cuban",
  "Lounge",
  "Impressionist",
  "Grime",
  "Guaracha",
  "Operetta",
  "Hip-House",
  "Goa Trance",
  "Ragtime",
  "Mandopop",
  "G-Funk",
  "Lovers Rock",
  "Éntekhno",
  "Chillwave",
  "Euro-Disco",
  "Gothic Metal",
  "Melodic Death Metal",
  "Brass Band",
  "Psychobilly",
  "Rhythmic Noise",
  "Nursery Rhymes",
  "Video Game Music",
  "Canzone Napoletana",
  "Goregrind",
  "Neo-Romantic",
  "Dialogue",
  "Deep Techno",
  "Symphonic Metal",
  "Medieval",
  "Tech Trance",
  "Cut-up/DJ",
  "Son",
  "Pacific",
  "Ragga",
  "Speedcore",
  "Guaguancó",
  "Twist",
  "Ragga HipHop",
  "Promotional",
  "Space-Age",
  "Honky Tonk",
  "Dream Pop",
  "Nordic",
  "Educational",
  "Atmospheric Black Metal",
  "Military",
  "Eurobeat",
  "Fado",
  "Political",
  "Hard Techno",
  "Melodic Hardcore",
  "New Jack Swing",
  "Funk Metal",
  "Music Hall",
  "Mariachi",
  "Acid Rock",
  "Highlife",
  "K-pop",
  "Soca",
  "Soukous",
  "Deathcore",
  "Sound Collage",
  "Makina",
  "Hawaiian",
  "Folk Metal",
  "Afro-Cuban Jazz",
  "Zouk",
  "Speech",
  "Organ",
  "Jazzdance",
  "Freetekno",
  "Monolog",
  "Romani",
  "Reggaeton",
  "Piano Blues",
  "Witch House",
  "Delta Blues",
  "Horrorcore",
  "Noisecore",
  "Modern Electric Blues",
  "Post-Metal",
  "City Pop",
  "J-Rock",
  "Cubano",
  "New Beat",
  "Anison",
  "Luk Thung",
  "Hands Up",
  "Bubblegum",
  "Coldwave",
  "Public Broadcast",
  "Vallenato",
  "Norteño",
  "Gypsy Jazz",
  "Viking Metal",
  "Forró",
  "Italo House",
  "Jumpstyle",
  "Bhangra",
  "No Wave",
  "Harmonica Blues",
  "Texas Blues",
  "Electroacoustic",
  "Boogaloo",
  "Therapy",
  "Special Effects",
  "Sound Art",
  "Speed Garage",
  "Cajun",
  "Corrido",
  "Enka",
  "Pub Rock",
  "Post-Modern",
  "Porro",
  "Oratorio",
  "Yé-Yé",
  "P.Funk",
  "Jump",
  "Blues",
  "Hillbilly",
  "Illbient",
  "Tejano",
  "Industrial Metal",
  "Bassline",
  "Pachanga",
  "Cloud Rap",
  "Rebetiko",
  "Descarga",
  "Depressive Black Metal",
  "Guajira",
  "Boogie Woogie",
  "Louisiana Blues",
  "Beguine",
  "Karaoke",
  "Power Violence",
  "Screw",
  "Technical Death Metal",
  "Andean Music",
  "Raï",
  "Donk",
  "Son Montuno",
  "Séga",
  "Groove Metal",
  "Deathrock",
  "Nueva Cancion",
  "Cantopop",
  "Min'yō",
  "Charanga",
  "Copla",
  "Western Swing",
  "Juke",
  "Chinese Classical",
  "Klezmer",
  "Sermon",
  "Crunk",
  "Horror Rock",
  "Technical",
  "Aboriginal",
  "Compas",
  "Alternative Metal",
  "DJ Battle Tool",
  "Catalan Music",
  "Disco Polo",
  "Pasodoble",
  "Jangle Pop",
  "Ghetto",
  "Népzene",
  "Electroclash",
  "Tropical House",
  "Carnatic",
  "Bachata",
  "Danzon",
  "Levenslied",
  "Health-Fitness",
  "Swingbeat",
  "Appalachian Music",
  "Funeral Doom Metal",
  "Conjunto",
  "Turntablism",
  "Bounce",
  "Minneapolis Sound",
  "Noise Rock",
  "Batucada",
  "Halftime",
  "Pornogrind",
  "Bayou Funk",
  "Free Funk",
  "Progressive Breaks",
  "Zydeco",
  "Música Criolla",
  "Sea Shanties",
  "Alt-Pop",
  "Bakersfield Sound",
  "Hokkien Pop",
  "Ethno-pop",
  "Quechua",
  "Indo-Pop",
  "Steel Band",
  "Footwork",
  "Musette",
  "Lambada",
  "Movie Effects",
  "J-Core",
  "Liscio",
  "Skiffle",
  "Swamp Pop",
  "Go-Go",
  "Early",
  "Sound Poetry",
  "Doomcore",
  "Axé",
  "Ghetto House",
  "Baião",
  "Pipe & Drum",
  "Cretan",
  "Huayno",
  "Miami Bass",
  "Choro",
  "Bleep",
  "Plena",
  "Latin Pop",
  "Gamelan",
  "Schranz",
  "Glitch Hop",
  "Kwaito",
  "Zarzuela",
  "Ghazal",
  "Balearic",
  "Mizrahi",
  "Kolo",
  "Ottoman Classical",
  "Erotic",
  "Persian Classical",
  "Nueva Trova",
  "Unblack Metal",
  "Samba-Canção",
  "Zamba",
  "Basque Music",
  "Britcore",
  "Trova",
  "Cabaret",
  "Barbershop",
  "Bengali Music",
  "Chamamé",
  "NDW",
  "Chacarera",
  "UKStreet Soul",
  "Group Sounds",
  "Ballet",
  "Gaita",
  "Ryūkōka",
  "Dangdut",
  "Memphis Blues",
  "Occitan",
  "Rock Opera",
  "Beatdown",
  "Hyperpop",
  "Chutney",
  "Neo Trance",
  "Reggae Gospel",
  "East Coast Blues",
  "Ghettotech",
  "Mo Lam",
  "Blackgaze",
  "Tamil Film Music",
  "Baroque Pop",
  "Exotica",
  "K-Rock",
  "Luk Krung",
  "Qawwali",
  "Joropo",
  "Twelve-tone",
  "Phonk",
  "Sertanejo",
  "Gusle",
  "Favela Funk",
  "Spirituals",
  "Kaseko",
  "Marimba",
  "Plunderphonics",
  "Dark Electro",
  "Nhạc Vàng",
  "Timba",
  "Dub Poetry",
  "Villancicos",
  "Hyphy",
  "Keroncong",
  "UK Funky",
  "Future House",
  "Andalusian Classical",
  "Morna",
  "Hiplife",
  "Guarania",
  "Piedmont Blues",
  "Cape Jazz",
  "Crossover thrash",
  "Sunshine Pop",
  "Maloya",
  "Mento",
  "Medical",
  "Baltimore Club",
  "Dark Jazz",
  "Jibaro",
  "Overtone Singing",
  "Sephardic",
  "Jota",
  "Future Bass",
  "Salegy",
  "Russian Pop",
  "Banda",
  "Lento Violento",
  "Phleng Phuea Chiwit",
  "Vaudeville",
  "Galician Traditional",
  "Izvorna",
  "Griot",
  "Marcha Carnavalesca",
  "Hard Beat",
  "Drill",
  "Bomba",
  "Mbalax",
  "Beatbox",
  "Electro Swing",
  "Candombe",
  "Serial",
  "Thai Classical",
  "Mugham",
  "Ambient House",
  "Slowcore",
  "Aguinaldo",
  "Nerdcore Techno",
  "Gagaku",
  "Zemer Ivri",
  "Stride",
  "Caipira",
  "Milonga",
  "Comfy Synth",
  "Deconstructed Club",
  "Funaná",
  "Skweee",
  "Ballroom",
  "Cuatro",
  "Cantorial",
  "Jersey Club",
  "Shaabi",
  "Champeta",
  "Mathcore",
  "Carimbó",
  "Sámi Music",
  "French House",
  "Kizomba",
  "Sonero",
  "Jug Band",
  "Bambuco",
  "Seresta",
  "Philippine Classical",
  "Post-Grunge",
  "Break-In",
  "Gwo Ka",
  "Yemenite Jewish",
  "Funkot",
  "Hypnagogic pop",
  "Cobla",
  "Occult",
  "Waiata",
  "Moombahton",
  "Mouth Music",
  "Junkanoo",
  "Rune Singing",
  "Geet",
  "Néo Kyma",
  "Shidaiqu",
  "Taarab",
  "Microhouse",
  "Piobaireachd",
  "Hill Country Blues",
  "Filk",
  "Frevo",
  "Bitpop",
  "Hyper Techno",
  "Korean Court Music",
  "Future Pop",
  "Rapso",
  "Low Bap",
  "Bubbling",
  "Kuduro",
  "Guggenmusik",
  "Gqom",
  "Rōkyoku",
  "Cambodian Classical",
  "Bangladeshi Classical",
  "Lao Music",
  "V-pop",
  "Lowercase",
  "Għana",
  "Klasik",
  "Neopagan",
  "Bongo Flava",
  "Amapiano",
  "Sean-nós",
  "Nintendocore",
  "Motswako",
  "Currulao",
  "Spaza",
  "Azonto",
  "Brit Pop",
  "Trallalero",
  "Zhongguo Feng",
  "Jiuta",
  "Honkyoku",
  "Shomyo",
  "Gogo",
  "Ojkača",
  "Sankyoku",
  "Sokyoku",
  "Shoegazer",
  "Shinkyoku",
  "Singeli",
];

export const countries = [
  "US",
  "UK",
  "Germany",
  "France",
  "Japan",
  "Italy",
  "Europe",
  "Canada",
  "Netherlands",
  "Spain",
  "Australia",
  "Russia",
  "Sweden",
  "Brazil",
  "Belgium",
  "Greece",
  "Poland",
  "Mexico",
  "Finland",
  "Jamaica",
  "Switzerland",
  "USSR",
  "Argentina",
  "Denmark",
  "Portugal",
  "Norway",
  "Austria",
  "Worldwide",
  "New Zealand",
  "UK & Europe",
  "South Africa",
  "Yugoslavia",
  "Colombia",
  "Czech Republic",
  "Hungary",
  "USA & Canada",
  "India",
  "Ukraine",
  "Turkey",
  "Venezuela",
  "Ireland",
  "Indonesia",
  "Chile",
  "South Korea",
  "Peru",
  "Israel",
  "Bulgaria",
  "Thailand",
  "Malaysia",
  "Scandinavia",
  "German Democratic Republic (GDR)",
  "China",
  "Hong Kong",
  "Croatia",
  "Philippines",
  "Serbia",
  "Ecuador",
  "USA & Europe",
  "Lithuania",
  "UK, Europe & US",
  "Germany, Austria, & Switzerland",
  "Singapore",
  "Slovenia",
  "Slovakia",
  "Uruguay",
  "Iceland",
  "Bolivia",
  "Australasia",
  "Australia & New Zealand",
  "UK & Ireland",
  "Nigeria",
  "Estonia",
  "USA, Canada & UK",
  "Benelux",
  "Panama",
  "Lebanon",
  "UK & US",
  "Pakistan",
  "Costa Rica",
  "Egypt",
  "Cuba",
  "Latvia",
  "Middle East",
  "Puerto Rico",
  "Kenya",
  "Iran",
  "Belarus",
  "Morocco",
  "Guatemala",
  "Saudi Arabia",
  "Barbados",
  "Trinidad & Tobago",
  "Czech Republic & Slovakia",
  "Bosnia & Herzegovina",
  "Luxembourg",
  "USA, Canada & UK",
  "Macedonia",
  "Zimbabwe",
  "Ghana",
  "Albania",
  "Honduras",
  "Kuwait",
  "Martinique",
  "Benin",
  "Sri Lanka",
  "Curaçao",
  "Andorra",
  "Congo, Republic of the",
  "Netherlands Antilles",
  "Malta",
  "Rhodesia",
  "Asia",
  "Mozambique",
  "Cyprus",
  "Mauritius",
  "Slovenia & Slovakia",
  "Singapore & Malaysia",
  "Northern America (inc Mexico)",
  "Dominican Republic",
  "Reunion",
  "Estonia",
  "Ivory Coast",
  "France & Benelux",
  "Tunisia",
  "Serbia and Montenegro",
  "Angola",
  "Georgia",
  "Syria",
  "Nicaragua",
  "Kazakhstan",
  "Paraguay",
  "Senegal",
  "Guadeloupe",
  "Ethiopia",
  "Vietnam",
  "UK & France",
  "Bahamas, The",
  "Suriname",
  "UK, Europe & Japan",
  "Moldova, Republic of",
  "Haiti",
  "South Vietnam",
  "Gulf Cooperation Council",
  "South America",
  "Cameroon",
  "Faroe Islands",
  "South East Asia",
  "Uzbekistan",
  "Azerbaijan",
  "Albania",
  "Guinea",
  "Dahomey",
  "Jersey",
  "UK, Europe & Japan",
  "Moldova, Republic of",
  "British Virgin Islands",
  "Montserrat",
  "Hong Kong & Thailand",
  "Abkhazia",
  "Djibouti",
  "Sao Tome and Principe",
  "Norfolk Island",
  "South Pacific",
  "British Virgin Islands",
  "Antigua & Barbuda",
  "Guam",
  "Central African Republic",
  "Qatar",
  "Somalia",
  "Liberia",
  "Macau",
  "Grenada",
  "Saint Lucia",
  "Sint Maarten",
  "Korea (pre-1945)",
  "Protectorate of Bohemia and Moravia",
  "Bhutan",
  "Southern Rhodesia",
  "Upper Volta",
  "USA, Canada & UK",
  "Benelux",
  "South Pacific",
  "West Bank",
  "Antarctica",
  "Equatorial Guinea",
  "Kiribati",
  "Chad",
  "Falkland Islands",
  "Gaza Strip",
  "American Samoa",
  "Northern Mariana Islands",
  "Southern Sudan",
  "Antarctica",
  "Equatorial Guinea",
  "Nauru",
  "Niue",
  "Pitcairn Islands",
  "Saint Pierre and Miquelon",
  "Tokelau",
  "Wallis and Futuna",
  "South West Africa",
  "Tonga",
  "Solomon Islands",
  "Turks and Caicos Islands",
  "Cook Islands",
  "Rwanda",
  "Samoa",
  "South Pacific",
  "West Bank",
];
